ALTER TABLE class_subjects ADD COLUMN day VARCHAR(10) DEFAULT NULL;
ALTER TABLE class_subjects ADD COLUMN start_time TIME DEFAULT NULL;
ALTER TABLE class_subjects ADD COLUMN end_time TIME DEFAULT NULL;
